- name: install nginx
  apt:
    name: nginx
    state: installed
    update_cache: true

- name: update nginx base configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx


