- hosts: all
  become: yes
  pre_tasks:
    - include_vars: variables.yml
    - include_vars: vault.yml
  tasks:
    - name: Add deployment user
      user:
        name: "{{ dep_user }}"
        password: "{{ dep_pass }}"

    - name: install packages
      apt:
        name: "{{ packages }}"
        state: installed
        update_cache: true

    - name: install setfacl support
      become: yes
      apt:
        pkg: acl

    - name: link to git
      git:
        repo: "{{ git_repo }}"
        dest: /home/{{ dep_user }}/deploy

    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      with_items: "{{ services }}"