- hosts: all
  become: yes
  pre_tasks:
    - include_vars: twotter_vars/variables.yml
    - include_vars: twotter_vars/vault.yml
  tasks:
    - name: Add deployment user
      user:
        name: "{{ dep_user }}"
        password: "{{ dep_pass }}"

    - name: install packages
      apt:
        name: "{{ packages }}"
        state: installed
        update_cache: true

    - name: install setfacl support
      become: yes
      apt: pkg=acl

    - name: link to git
      git:
        repo: "{{ git_repo }}"
        dest: /home/{{ dep_user }}/deploy

    - name: copy php.ini file
      copy:
        src: /home/{{ dep_user }}/deploy/php.ini
        dest: /etc/php/7.0/fpm/php.ini
        remote_src: true

    - name: get composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer.phar
        warn: false
    
    - name: create link /usr/local/bin/composer to phar
      file:
        path: /usr/local/bin/composer
        src: /usr/local/bin/composer.phar
        state: link

    - name: update composer
      shell: /usr/local/bin/composer.phar self-update
      register: composer_update_result
      changed_when: "'Updating to version' in composer_update_result.stdout"

    - name: copy default nginx config file
      copy:
        src: /home/{{ dep_user }}/deploy/playbook-files/nginx.conf
        dest: /etc/nginx/sites-available/default
        remote_src: true

    - name: Install composer
      composer: 
        command: install
        working_dir: /home/{{ dep_user }}/deploy

    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      with_items: "{{ services }}"

    - name: Create Database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "{{ dep_db }}"

    - name: Create User
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ dep_user }}"
        password: "{{ dep_pass }}"
        state: present
        role_attr_flags: SUPERUSER,CREATEDB

    - name: Provide user with DB permissions
      become: yes
      become_user: postgres
      postgresql_user:
        user: "{{ dep_user }}"
        db: "{{ dep_db }}"
        priv: ALL

    - template:
        src: playbook-files/config.php.j2
        dest: /home/{{ dep_user }}/deploy/app/config.php
