- name: install postgres
  apt:
    name: postgresql
    state: installed
    update_cache: true

- name: install postgresql package
  apt:
    pkg: python-psycopg2
    state: latest
  notify:
    - restart postgres

- name: update pg_hba.conf configuration
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf
  notify:
    - restart postgresql

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Create User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    role_attr_flags: SUPERUSER,CREATEDB

- name: Provide user with DB permissions
  become: yes
  become_user: postgres
  postgresql_user:
    user: "{{ db_user }}"
    db: "{{ db_name }}"
    priv: ALL

- name: restart postgres
  service:
    name: postgresql
    state: restarted