- name: install postgres
  apt:
    name: postgresql
    state: installed
    update_cache: true

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_user }}"

- name: Create User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    role_attr_flags: SUPERUSER,CREATEDB

- name: Provide user with DB permissions
  become: yes
  become_user: postgres
  postgresql_user:
    user: "{{ db_user }}"
    db: "{{ db_name }}"
    priv: ALL

- name: restart postgres
  service:
    name: postgresql
    state: restarted