Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
    
  config.vm.network "forwarded_port", guest: 80, host: 9191
    
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    ansible.vault_password_file = "../ansible/vault_pass.txt"
  end
end

